FROM node:alpine

ARG DATABASE_URL
ENV DATABASE_URL=$DATABASE_URL

ARG NEXTAUTH_SECRET="123456"
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ARG NEXTAUTH_URL="http://localhost:3000"
ENV NEXTAUTH_URL=$NEXTAUTH_URL

ARG DISCORD_CLIENT_ID
ENV DISCORD_CLIENT_ID=$DISCORD_CLIENT_ID
ARG DISCORD_CLIENT_SECRET
ENV DISCORD_CLIENT_SECRET=$DISCORD_CLIENT_SECRET

ARG PERSISTENT_REDIS_URI
ENV PERSISTENT_REDIS_URI=$PERSISTENT_REDIS_URI
ARG PERSISTENT_REDIS_MODE
ENV PERSISTENT_REDIS_MODE=$PERSISTENT_REDIS_MODE

ARG EVENT_REDIS_URI
ENV EVENT_REDIS_URI=$EVENT_REDIS_URI
ARG EVENT_REDIS_MODE
ENV EVENT_REDIS_MODE=$EVENT_REDIS_MODE

ARG REDIS_URI
ENV REDIS_URI=$REDIS_URI
ARG REDIS_MODE
ENV REDIS_MODE=$REDIS_MODE

ARG S3_STORAGE_ACCESS_KEY
ENV S3_STORAGE_ACCESS_KEY=$S3_STORAGE_ACCESS_KEY
ARG S3_STORAGE_SECRET_KEY
ENV S3_STORAGE_SECRET_KEY=$S3_STORAGE_SECRET_KEY
ARG S3_STORAGE_REGION
ENV S3_STORAGE_REGION=$S3_STORAGE_REGION
ARG S3_STORAGE_BUCKET
ENV S3_STORAGE_BUCKET=$S3_STORAGE_BUCKET
ARG S3_STORAGE_ENDPOINT
ENV S3_STORAGE_ENDPOINT=$S3_STORAGE_ENDPOINT
ARG S3_STORAGE_PORT
ENV S3_STORAGE_PORT=$S3_STORAGE_PORT
ARG S3_STORAGE_SECURE
ENV S3_STORAGE_SECURE=$S3_STORAGE_SECURE

ARG NEXT_PUBLIC_RESOURCES_URL
ENV NEXT_PUBLIC_RESOURCES_URL=$NEXT_PUBLIC_RESOURCES_URL

COPY . ./app/
WORKDIR /app
ENV NODE_ENV production
RUN npm install
RUN npx prisma generate
RUN npm run build
EXPOSE 3000
CMD [ "npm", "run", "start" ]
